name: Test
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Install dependencies
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: tidy
      - name: Install kubectl-package command
        run: |
          wget https://github.com/package-operator/package-operator/releases/download/v1.5.0/kubectl-package_linux_amd64
          chmod +x kubectl-package_linux_amd64
          mv kubectl-package_linux_amd64 /bin/kubectl-package
      - name: Run unit tests
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: test:unit
      - name: Run integration tests
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: test:integration