name: tests
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  lint-unit-integration:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.20.0'

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install kubectl-package command
      run: |
        wget https://github.com/package-operator/package-operator/releases/download/v1.5.0/kubectl-package_linux_amd64
        chmod +x kubectl-package_linux_amd64
        sudo mv kubectl-package_linux_amd64 /bin/kubectl-package

    - name: Lint
      run: ./mage test:lint

    - name: Unit
      run: ./mage test:unit

    - name: Integration
      run: ./mage test:integration
